### ISSUE TITLE
Wyatt running the application locally.

### ISSUE THREAD

**Issue by jtperreault** [jtperreault/political_ties#1]
Hi Wyatt,

I was wondering if you wanted to collaborate on a project with me via github to gain a little experience with the workflow.

I generated a new [Rails](https://github.com/rails/rails) application here for us to work on. It's just the bare bones for now but we'll add to it in the future. You'll need to install a few things on your local machine to get the application up and running.

- [x] Install Ruby, version 2.2.2 or greater
- [x] Install Postgresql

Once you have those items installed and working on your machine you'll want to run the `bundle` command in the application directory to install the necessary Ruby gems, then run `rails server` to start up the local development server. After that you should be able to see the application running locally by visiting [the page locally](http://localhost:3000).

Once you're able to see the Rails welcome page we can close this issue. If you encounter any problems along the way try to solve them yourself, if you need some help though please feel free to leave a comment on this issue and I'll respond as soon as I'm able.

**Comment by wymillerlinux** [comment]
Hey James,

Okay so alot of installation and preparation went into getting my Rails environment installed, especially PostgreSQL but hey I can finally see the Rails welcome page! ![ruby on rails - chromium_002](https://cloud.githubusercontent.com/assets/7097034/21027050/2d91ef9e-bd5d-11e6-9a23-0d0a3f424d81.png)
I think you can close this issue, this task took me about an hour to complete because I haven't used PostgreSQL before (I have used MySQL though...).

**Comment by jtperreault** [comment]
Excellent work @wymillerlinux! It always takes a bit of work to bootstrap a development environment but I'm glad to see it you got it running without much problem. I will be adding additional Github issues with tasks for you to complete to help you become more familiar with the layout of Rails applications.

_**Side note**: Rails is database agnostic so we could have used (or in the future switch to) MySQL or any other number of DBs! I prefer PostgreSQL because it has some neat features including a [native JSON datatype](https://www.postgresql.org/docs/9.5/static/datatype-json.html)._
