### ISSUE TITLE
The Repository should have a style guide

### ISSUE THREAD

**Issue by jtperreault** [jtperreault/political_ties#10]
Should setup Hound or similar to automatically check open PRs and comment on style violations.

**Comment by wymillerlinux** [comment]
I have created a rubocop and hound configuration files if you would like to review my latest commit which is on the feature branch. Note that I have not made a pull request as changes will probably have to be made.

**Comment by jtperreault** [comment]
@wymillerlinux go ahead and open the PR regardless. both of us can push to the working branch and the PR updates automatically.

It would make sense for hound to read from the rubocop conf, hopefully we only need one and not both confs

**Comment by wymillerlinux** [comment]
PR #15 resolves this issue :+1:
