### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by jtperreault** [jtperreault/political_ties#3]
Hey @wymillerlinux, next task for you is to get the automated test suite running and get that integration test you merged in passing! There are several steps to complete this which I will outline for you with notes. If you get hung up (or have general questions) please leave a comment and tag me so I can reply. I've been doing this for a while so it's very likely that any issues you encounter I've already dealt with at some point and I'm happy to help. We are going to **run the tests after each step** and let the failure messages guide our development, this is how we do TDD (test driven development).

1. Run the test suite. Unless you've already created the databases the test suite will crash and burn, without ever running our test, because it cannot connect to the test database. If you experience this problem (you likely will) then you'll want to run the built in Rails command to create the development and test databases, `rails db:create`. Running the test suite again _should_ give you a failing message with some details.
- [x] Run the test suite (failing).

2. After completing number 1 you should see the test suite failing with a message about no route matching `[GET] /wyatt`, let's fix that. You'll be editing the [routes file](https://github.com/jtperreault/political_ties/blob/master/config/routes.rb), there is a comment there outlining where to find help.
- [x] Create the `/wyatt` route in the routes file, map it to a controller and method that does not yet exist.

3. Run the test suite again. It should fail with a new message about a missing constant (failure message depends on what you mapped the route too). Let's fix this issue, next step is to create the controller. Please read the [Action Controller Overview](http://guides.rubyonrails.org/action_controller_overview.html) for controller information, naming conventions, etc.
- [x] Create a controller to satisfy test's error message.

4. Run the test suite again. Our failure message should change, indicating that while the test now found the controller it couldn't find the method you tried to execute. So, you guessed it, lets add the method. You should be able to add just the method, no code inside it to satisfy this failure.
- [x] Create a method to satisfy our test suite's failure.

5. After you run the test again your failure should indicate that it couldn't find the template, so let's add that. Add a directory inside the `app/views` directory that matches your controller name, so if your controller is called `WyattController` we'll add a directory called `wyatt`. Inside the new directory you'll create a template that matches the method name, `<method_name>.html.erb` the file name means that the file will be processed first by `erb` which is Ruby, and then made into an html file.
- [x] Create a ERB template view.

6. The new test failure shows it looked for a paragraph tag but didn't find one, fix that by adding a paragraph tag to the template.
- [x] Add a paragraph tag to the template.

7. Your test should fail now letting you know it expected to find 'Hi James!' inside the paragraph tag but did not.
- [x] Add the 'Hi James!' text to the paragraph tag.

8. We did a lot of work here, but at this point you should have a passing test! Well done, pat yourself on the back :)
- [x] Passing test!

**Comment by wymillerlinux** [comment]
Hey @jtperreault, Happy Holidays! Sorry I didn't tell you earlier before Christmas...
Okay so, I got the test working by watching some tutorials on Rails and some Googling (mostly Googling), and it's a passing test. However, when I was generating a controller (via `rails generate controller`), the name for the controller was `wyatt_controller`, not `wyatt`. Also, the path isn't `/wyatt` rather it is `/wyatt_controller/index`. I would like to know if you can fix that by the `rails generate controller` so I understand the command a bit better. But it is working! I'm so excited right now! My first website, written in Ruby; it's so cool! Anyway, um, do what you will to this issue, I think it can be closed.

**Comment by wymillerlinux** [comment]
@jtperreault I just pushed my local repo to the project repo, you can review my files in the [latest commit.](https://github.com/jtperreault/political_ties/commit/e02cb8849caa69f3fdb095d268602fc686495dfc) Note that I did this on a Windows machine so that's why Gemfile is changed.

**Comment by jtperreault** [comment]
@wymillerlinux Pull request would have been ideal. In the future you should plan on **ALWAYS** making a branch and doing your work there, then opening a PR to master. You never ever want to commit directly to the master branch.

**Comment by jtperreault** [comment]
@wymillerlinux I'm trying to think of how to undo your commits without too much trouble.

One solution would be to do a `git reset` on your `master` branch locally and then `git push -f` to send the master branch back without your latest commits. Then you could `git checkout -b branch_name` and commit the changes and send that branch up to github so I can review and comment. Thoughts?

**Comment by wymillerlinux** [comment]
@jtperrault, I made a pull request! You should go look at it 👍 I gotta learn git sooner or later...

**Comment by wymillerlinux** [comment]
Closing issue because #9 is now merged.
