### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jtperreault** [jtperreault/political_ties#4]
- [x] Ruby version

- [x] Database information

- [x] Running the test suite

- [ ] Contributing

**Comment by wymillerlinux** [comment]
Opened a pull request because I felt like editing the README and because I needed to relieve some stress. Long weekend at work.

**Comment by jtperreault** [comment]
👍 Thanks @wymillerlinux!

**Comment by wymillerlinux** [comment]
@jtperreault I have updated the README per your instructions.

**Comment by wymillerlinux** [comment]
Closing issue because #7 is now merged.
